### ISSUE TITLE
Why is 0.4 not tagged as latest release? Why no jar?

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/wdltool#10]
Right now 0.1 is tagged as latest release and is the only one that comes with a precompiled jar. Is there any reason for this? Since it takes several non-standard (for end users) dependencies to build wdltool, it would be super helpful to provide a jar file.

**Comment by vdauwera** [comment]
For the record, this is key to enabling end users to use the latest and best. For example the latest version (0.5 built from source) succeeds in validating a WDL that 0.1 chokes on for no good reason -- would be a shame for people to waste their time trying to troubleshoot something that is due to a bug in an old version of the validation tool :\

**Comment by geoffjentry** [comment]
@vdauwera Can you look to see if what's there works for you? If so, go ahead and close this. If not let me know what else I should do.

**Comment by vdauwera** [comment]
Yes, perfect -- thanks @geoffjentry !
