### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/wdltool#20]
I had a few issues that were fixed by building the latest from source. There's a good chance that will also be the case for the other issues that have been reported. Would be good to cut a release to make it available without requiring people to build from source.

**Comment by knoblett** [comment]
Are we responsible for building a new release now that we own this repo? Or am I misremembering?

**Comment by ruchim** [comment]
The wdltool release is a part of the Cromwell release process

**Comment by knoblett** [comment]
Ah, thank you, that makes sense. @vdauwera do we still need a release? The most recent release was done 3 days prior to the creation of this ticket.

**Comment by vdauwera** [comment]
Does the release process include making a packaged jar? I think my problem was that there wasn't a jar that corresponded to the latest releases version available for download, come to think of it.

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2872](https://github.com/broadinstitute/cromwell/issues/2872) via [**ZenHub**](https://www.zenhub.com/)
