### ISSUE TITLE
wdltool validate foo.wdl exits with status 0 when foo.wdl is not valid 

### ISSUE THREAD

**Issue by tbl3rd** [broadinstitute/wdltool#27]
If validate's status indicated failure with a nonzero exit status,
one could script more conveniently.

``` shell
#!/bin/sh
if java -jar wdltool.jar validate foo.wdl
then
    java -jar Cromwell.jar run foo.wdl inputs.json
fi
```

**Comment by katevoss** [comment]
@tbl3rd sounds like a bug to me, agreed?

**Comment by vdauwera** [comment]
Labeling it a bug seems a bit harsh to me but it would def be an improvement to return a non-zero code.

**Comment by katevoss** [comment]
Thanks for the clarification, recategorizing it.

**Comment by tlangs** [comment]
bump?

**Comment by pshapiro4broad** [comment]
The code was written to support a nonzero exit code, but the author forgot that you have to call `exit()` explicitly from Scala to return a non-zero exit code. I'll submit a PR with the fix.

**Comment by mcovarr** [comment]
fixed
