### ISSUE TITLE
validate fails with "head of empty list"

### ISSUE THREAD

**Issue by MatthewMah** [broadinstitute/wdltool#28]
I am trying to validate a wdl file and expecting exactly one of:
1. no output -> validated
2. intelligible message explaining why wdl file is invalid

I am running:
`java -jar wdltool-0.4.jar validate wdlFailure.wdl`

I get `head of empty list`, which appears to be a bug in the wdltool. 

wdlFailure.wdl
```
workflow sampleError{
	call simple_read_string{}
}

task simple_read_string{	
	command{
		echo "testing" > testing_file
	}
	output{
		String out = read_string(testing_file)
	}
}
```

I think the `read_string` call should be `read_string("./testing_file")`.

**Comment by geoffjentry** [comment]
Hi @MatthewMah - can you run this against a more modern version of the tool? For instance I'm getting:

```orcus:wdltool gentrj$ java -jar target/scala-2.12/wdltool-0.10.jar validate mah.wdl
ERROR: Variable testing_file does not reference any declaration in the task (line 10, col 28):

		String out = read_string(testing_file)
                           ^

Declaration starts here (line 10, col 10):

		String out = read_string(testing_file)
         ^
```
