### ISSUE TITLE
wdltool 0.10 validates too generously

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/wdltool#29]
Given a task:

task myTask {
  File f
  command {
     touch ${f.bam.bai}
  }
}

A workflow with such a task validates in wdltool-0.10 but when run on cromwell-26, it fails with an error: java.lang.UnsupportedOperationException: Could not evaluate expression:....

Given a slightly altered version of that previous task:

task myTask {
  File f
  command {
     touch ${f%%.bam.bai}
  }
}

This task also validates but fails before the Workflow is about to run with the error: scala.MatchError: null

**Comment by geoffjentry** [comment]
Is this an artifact of wdltool being out of synch? it happens way too often :(

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2873](https://github.com/broadinstitute/cromwell/issues/2873) via [**ZenHub**](https://www.zenhub.com/)
