### ISSUE TITLE
Include a runnable jar in the release

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/wdltool#4]
We need to be able to point users to a pre-baked jar that's ready to run.

**Comment by geoffjentry** [comment]
Should be attached - closing the issue. If I've hosed it up or that's not what you wanted reopen it on me :)

**Comment by vdauwera** [comment]
Great, it's there now. Thanks!

(it wasn't there before, was it?)

**Comment by geoffjentry** [comment]
nope!

**Comment by vdauwera** [comment]
OK, glad I'm not crazy/blind.
