### ISSUE TITLE
Validation response is "null"

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/wdltool#46]
When validating the workflow below with wdltool-0.14.jar, the response is simply "null". 

```
workflow w {
  String s = "test"

  output {
    String o =
  }
}
```
It would be great if a more comprehensive error is returned in the case of invalid workflow outputs.

**Comment by mcovarr** [comment]
Issue moved to [broadinstitute/cromwell #2883](https://github.com/broadinstitute/cromwell/issues/2883) via [**ZenHub**](https://www.zenhub.com/)
